import { useEffect, useState } from 'react';
import { ChevronLeft, Edit3, File, FileCode2, Folder, FolderOpen, FolderPlus, Home, Image, Music, Search, Trash2, Video } from 'lucide-react';
import { formatBytes, formatDate } from '../lib/format';
function iconFor(item:any){if(item.isDirectory)return Folder;if(['png','jpg','jpeg','webp','gif','svg'].includes(item.extension))return Image;if(['mp4','mkv','mov','webm'].includes(item.extension))return Video;if(['mp3','wav','flac','m4a'].includes(item.extension))return Music;if(['js','jsx','ts','tsx','json','css','html','py','cs','java','md','txt','log','xml','yml','yaml'].includes(item.extension))return FileCode2;return File}
export default function FilesApp(){
 const[data,setData]=useState<any>({path:'',parent:'',items:[]}),[query,setQuery]=useState(''),[selected,setSelected]=useState<any>(null),[preview,setPreview]=useState<any>(null),[busy,setBusy]=useState(false),[drives,setDrives]=useState<any[]>([]);
 const load=async(target?:string)=>{setBusy(true);try{const p=target||await window.nova.files.home();setData(await window.nova.files.list(p));setSelected(null);setPreview(null)}catch(e:any){window.alert(e?.message||'Unable to open folder.')}finally{setBusy(false)}};
 useEffect(()=>{load();window.nova.storage.drives().then(setDrives).catch(()=>{})},[]);
 useEffect(()=>{if(!selected||selected.isDirectory){setPreview(null);return}window.nova.files.preview(selected.path).then(setPreview).catch(()=>setPreview(null))},[selected]);
 const visible=data.items.filter((item:any)=>item.name.toLowerCase().includes(query.toLowerCase()));
 const choose=async()=>{const p=await window.nova.files.chooseFolder();if(p)load(p)};
 const createFolder=async()=>{const name=window.prompt('New folder name');if(!name)return;try{await window.nova.files.newFolder(data.path,name);await load(data.path)}catch(e:any){window.alert(e?.message||'Could not create folder.')}};
 const remove=async()=>{if(!selected||!window.confirm(`Move “${selected.name}” to Trash/Recycle Bin?`))return;try{await window.nova.files.trash(selected.path);await load(data.path)}catch(e:any){window.alert(e?.message||'Could not move item to trash.')}};
 const rename=async()=>{if(!selected)return;const name=window.prompt('Rename item',selected.name);if(!name||name===selected.name)return;try{await window.nova.files.rename(selected.path,name);await load(data.path)}catch(e:any){window.alert(e?.message||'Rename failed.')}};
 return <div className="app-shell files-app"><div className="file-toolbar"><button onClick={()=>load(data.parent)} title="Back"><ChevronLeft size={17}/></button><button onClick={()=>load()} title="Home"><Home size={16}/></button><button onClick={choose} title="Choose folder"><FolderOpen size={16}/></button><div className="path-box mono">{data.path||'Loading...'}</div><label className="search-box small"><Search size={15}/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Filter folder"/></label><button onClick={createFolder} title="New folder"><FolderPlus size={16}/></button></div>
 <div className="files-layout"><aside className="files-sidebar"><span className="eyebrow">LOCATIONS</span><button onClick={()=>load()}><Home size={16}/>Home</button><button onClick={choose}><FolderOpen size={16}/>Choose Folder</button><span className="eyebrow drive-label">THIS PC</span>{drives.map((drive:any)=><button key={`${drive.fs}-${drive.mount}`} onClick={()=>load(drive.mount||drive.fs)}><Folder size={16}/>{drive.mount||drive.fs}</button>)}<div className="privacy-hint">NOVA browses local files through its protected main process.</div></aside>
 <section className="file-list surface"><div className="file-head"><span>Name</span><span>Size</span><span>Modified</span></div>{busy?<div className="empty-state">Reading folder…</div>:visible.map((item:any)=>{const Icon=iconFor(item);return <button key={item.path} className={`file-row ${selected?.path===item.path?'selected':''}`} onClick={()=>setSelected(item)} onDoubleClick={()=>item.isDirectory?load(item.path):window.nova.files.open(item.path)}><span className="file-name"><Icon size={18}/>{item.name}</span><span>{item.isDirectory?'—':formatBytes(item.size)}</span><span>{formatDate(item.modified)}</span></button>})}{!busy&&!visible.length&&<div className="empty-state">No matching files in this folder.</div>}</section>
 <aside className="file-inspector surface">{selected?<><span className="eyebrow">INSPECTOR</span>{(()=>{const Icon=iconFor(selected);return <div className="preview-icon"><Icon size={34}/></div>})()}<h3>{selected.name}</h3><p className="mono muted wrap">{selected.path}</p>{preview?.type==='text'&&<pre className="file-text-preview">{String(preview.content||'').slice(0,5000)}</pre>}<div className="property-list"><div><span>Type</span><strong>{selected.isDirectory?'Folder':selected.extension?.toUpperCase()||'File'}</strong></div><div><span>Size</span><strong>{selected.isDirectory?'—':formatBytes(selected.size)}</strong></div><div><span>Modified</span><strong>{formatDate(selected.modified)}</strong></div></div><div className="stack-actions"><button className="primary-button" onClick={()=>selected.isDirectory?load(selected.path):window.nova.files.open(selected.path)}>Open</button><button className="ghost-button" onClick={rename}><Edit3 size={14}/>Rename</button><button className="ghost-button" onClick={()=>window.nova.files.reveal(selected.path)}>Reveal</button><button className="danger-link" onClick={remove}><Trash2 size={15}/>Move to trash</button></div></>:<div className="empty-state">Select a file or folder to inspect it.</div>}</aside></div></div>
}
