import { useEffect, useState } from 'react';
import { FolderOpen, HardDrive, ScanSearch } from 'lucide-react';
import { formatBytes, formatPercent } from '../lib/format';

export default function StorageApp(){
  const [drives,setDrives]=useState<any[]>([]); const [scan,setScan]=useState<any>(null); const [scanning,setScanning]=useState(false);
  useEffect(()=>{ window.nova.storage.drives().then(setDrives).catch(()=>{}); },[]);
  const analyze=async()=>{const root=await window.nova.files.chooseFolder(); if(!root)return; setScanning(true); setScan(null); try{setScan(await window.nova.storage.scan(root));}catch(e:any){window.alert(e?.message||'Scan failed.');}finally{setScanning(false)}};
  return <div className="app-shell"><div className="page-head compact"><div><span className="eyebrow">STORAGE CENTER</span><h1>Drives & analysis</h1><p>Inspect capacity, largest folders and file types.</p></div><button className="primary-button" onClick={analyze}><ScanSearch size={16}/>{scanning?'Scanning…':'Analyze folder'}</button></div>
    <div className="drive-grid">{drives.map(d=><section className="surface drive-card" key={`${d.fs}-${d.mount}`}><div className="drive-card-icon"><HardDrive size={21}/></div><div className="drive-card-head"><div><strong>{d.mount||d.fs}</strong><small>{d.type||'Local drive'}</small></div><b>{formatPercent(d.use)}</b></div><div className="progress large"><i style={{width:`${Math.min(100,Number(d.use||0))}%`}}/></div><div className="drive-numbers"><span>{formatBytes(d.used)} used</span><span>{formatBytes(d.available)} free</span></div></section>)}</div>
    <section className="surface scan-panel">{scanning?<div className="scan-loading"><span className="scan-orb"/><h2>Scanning selected folder</h2><p>Large directory scans are capped to keep NOVA responsive.</p></div>:scan?<><div className="section-title"><div><span>ANALYSIS</span><h3 className="mono wrap">{scan.root}</h3></div><div className="scan-stat"><strong>{formatBytes(scan.totalSize)}</strong><small>{scan.scannedEntries.toLocaleString()} entries scanned{scan.capped?' · capped':''}</small></div></div><div className="scan-grid"><div><span className="eyebrow">LARGEST FOLDERS</span>{scan.topFolders.slice(0,8).map((f:any)=><div className="rank-row" key={f.path}><span><FolderOpen size={15}/>{f.name}</span><strong>{formatBytes(f.size)}</strong></div>)}</div><div><span className="eyebrow">LARGEST FILES</span>{scan.largest.slice(0,8).map((f:any)=><div className="rank-row" key={f.path}><span className="truncate">{f.name}</span><strong>{formatBytes(f.size)}</strong></div>)}</div><div><span className="eyebrow">BY EXTENSION</span>{scan.byType.slice(0,8).map((t:any)=><div className="rank-row" key={t.extension}><span>.{t.extension}</span><strong>{formatBytes(t.size)}</strong></div>)}</div></div></>:<div className="scan-empty"><HardDrive size={38}/><h2>Analyze any folder</h2><p>Choose a folder to calculate its size, largest children and largest files. Nothing is uploaded.</p><button className="ghost-button" onClick={analyze}><FolderOpen size={16}/>Choose folder</button></div>}</section>
  </div>;
}
