import { useMemo, useRef, useState } from 'react';
import { AlertTriangle, ArrowRight, Bell, Bot, CheckCircle2, CircleDot, Clock3, DatabaseBackup, FileCheck2, Filter, Globe2, Play, RotateCcw, Search, ShieldCheck, ShieldOff, Sparkles, Swords, TerminalSquare, X } from 'lucide-react';
import Sidebar, { type Page } from './components/Sidebar';
import KpiCard from './components/KpiCard';
import MachineCard from './components/MachineCard';
import StatusPill from './components/StatusPill';
import Timeline from './components/Timeline';
import Topology from './components/Topology';
import AttackGraph from './components/AttackGraph';
import { initialMachines } from './data/machines';
import { scenarios } from './data/scenarios';
import { buildScenario, isolateAffected, recoverAffected } from './services/demoEngine';
import type { Incident, Machine, TimelineEvent } from './types';

export default function App(){
  const [page,setPage]=useState<Page>('command');
  const [machines,setMachines]=useState<Machine[]>(initialMachines);
  const [incident,setIncident]=useState<Incident|null>(null);
  const [events,setEvents]=useState<TimelineEvent[]>([]);
  const [selected,setSelected]=useState<Machine|null>(null);
  const [running,setRunning]=useState<string|null>(null);
  const timers=useRef<number[]>([]);
  const critical=machines.filter(m=>m.status==='COMPROMISED').length;
  const risky=machines.filter(m=>['SUSPICIOUS','HIGH_RISK','COMPROMISED'].includes(m.status)).length;
  const securityScore=Math.max(12,100-machines.reduce((a,m)=>a+Math.max(0,m.risk-20)/10,0)-critical*8)|0;

  const stopTimers=()=>{timers.current.forEach(clearTimeout);timers.current=[]};
  const reset=()=>{stopTimers();setMachines(initialMachines.map(m=>({...m,status:'HEALTHY',risk:8,alerts:0})));setIncident(null);setEvents([]);setRunning(null)};
  const startScenario=(id:string)=>{
    reset();setRunning(id);setPage('warroom');
    const fresh=initialMachines.map(m=>({...m,status:'HEALTHY' as const,risk:8,alerts:0}));
    const built=buildScenario(id,fresh);setIncident(built.incident);let state:any={machines:fresh,incident:built.incident};
    built.steps.forEach((step,idx)=>{const t=window.setTimeout(()=>{state=step(state);setMachines(state.machines);setIncident(state.incident);if(state.liveEvent)setEvents(v=>[...v,state.liveEvent]);if(idx===built.steps.length-1)setRunning(null)},900+idx*1350);timers.current.push(t)});
  };
  const contain=()=>{if(!incident)return;setMachines(m=>isolateAffected(m,incident));setIncident(i=>i?{...i,status:'CONTAINING'}:i);const e={id:'contain-'+Date.now(),time:new Date().toLocaleTimeString([],{hour12:false}),source:'Response Orchestrator',machine:incident.assets.join(', '),title:'Containment action approved',detail:'Affected laboratory assets were placed into simulated network isolation. No external systems were contacted.',severity:'HIGH' as const,tactic:'Containment'};setEvents(v=>[...v,e]);setIncident(i=>i?{...i,timeline:[...i.timeline,e]}:i)};
  const recover=()=>{if(!incident)return;setMachines(m=>recoverAffected(m,incident));setIncident(i=>i?{...i,status:'CLOSED',risk:9,confidence:99}:i);const e={id:'recover-'+Date.now(),time:new Date().toLocaleTimeString([],{hour12:false}),source:'Recovery Orchestrator',machine:'BACKUP-01',title:'Recovery verification complete',detail:'Clean lab snapshots were restored. Expected files match, no unexpected artifacts remain, and service health checks passed.',severity:'LOW' as const,tactic:'Recovery'};setEvents(v=>[...v,e]);setIncident(i=>i?{...i,timeline:[...i.timeline,e]}:i)};

  return <div className="app-shell"><Sidebar page={page} setPage={setPage}/><main className="main"><header className="topbar"><div><div className="eyebrow">ENTERPRISE CYBER DEFENSE PLATFORM</div><h1>{titleFor(page)}</h1></div><div className="top-actions"><div className={`threat-level ${critical?'elevated':''}`}><CircleDot size={14}/> THREAT LEVEL: {critical?'HIGH':risky?'ELEVATED':'NORMAL'}</div><button className="icon-btn"><Search size={18}/></button><button className="icon-btn"><Bell size={18}/>{critical>0&&<i/>}</button><div className="avatar">SA</div></div></header>
  <section className="content">
    {page==='command'&&<Command securityScore={securityScore} critical={critical} risky={risky} machines={machines} incident={incident} events={events} setPage={setPage}/>} 
    {page==='warroom'&&<WarRoom machines={machines} incident={incident} events={events} running={running} onContain={contain} onReset={reset}/>} 
    {page==='incidents'&&<Incidents incident={incident} events={events} setPage={setPage}/>} 
    {page==='machines'&&<Machines machines={machines} selected={selected} setSelected={setSelected}/>} 
    {page==='network'&&<NetworkPage machines={machines} events={events}/>} 
    {page==='investigation'&&<Investigation incident={incident} events={events}/>} 
    {page==='forensics'&&<Forensics incident={incident} events={events}/>} 
    {page==='intel'&&<Intel incident={incident}/>} 
    {page==='mitre'&&<Mitre incident={incident}/>} 
    {page==='recovery'&&<Recovery incident={incident} machines={machines} onContain={contain} onRecover={recover}/>} 
    {page==='range'&&<Range running={running} onStart={startScenario} onReset={reset}/>} 
    {page==='ai'&&<AI incident={incident} events={events}/>} 
    {page==='reports'&&<Reports incident={incident}/>} 
    {page==='users'&&<Users/>} 
    {page==='settings'&&<Settings/>}
  </section></main></div>
}

function titleFor(p:Page){return ({command:'Command Center',warroom:'Incident War Room',incidents:'Incident Operations',machines:'Machine Control Center',network:'Network Defense',investigation:'Investigation Graph',forensics:'Digital Forensics',intel:'Threat Intelligence',mitre:'MITRE Coverage',recovery:'Recovery Center',range:'Cyber Range',ai:'TITAN AI Analyst',reports:'Security Reports',users:'Users & RBAC',settings:'Platform Settings'} as Record<Page,string>)[p]}

function Command({securityScore,critical,risky,machines,incident,events,setPage}:any){return <><div className="kpi-grid"><KpiCard label="SECURITY POSTURE" value={<>{securityScore}<small>/100</small></>} sub={securityScore>85?'Environment inside normal baseline':'Active investigation reduces current posture'}/><KpiCard label="CRITICAL ASSETS" value={critical} sub={`${risky} assets currently outside healthy baseline`} accent={critical?'ACTION REQUIRED':'CLEAR'}/><KpiCard label="PROTECTED MACHINES" value={`${machines.filter((m:Machine)=>m.status!=='COMPROMISED').length}/20`} sub="Endpoint & network telemetry coverage"/><KpiCard label="ACTIVE INCIDENT" value={incident?incident.id.split('-').pop():'0'} sub={incident?incident.title:'No active incident'} accent={incident?.severity}/></div>
<div className="dashboard-grid"><section className="panel span-2"><div className="panel-head"><div><span className="panel-kicker">LIVE INFRASTRUCTURE</span><h2>Enterprise Attack Surface</h2></div><button className="text-btn" onClick={()=>setPage('warroom')}>Open war room <ArrowRight size={15}/></button></div><Topology machines={machines}/></section><section className="panel"><div className="panel-head"><div><span className="panel-kicker">CORRELATED EVENTS</span><h2>Live Detection Feed</h2></div><span className="live-chip"><i/>LIVE</span></div><div className="feed">{events.length?[...events].reverse().slice(0,7).map((e:TimelineEvent)=><div className="feed-row" key={e.id}><span className={`sev-dot sev-${e.severity.toLowerCase()}`}/><div><b>{e.title}</b><small>{e.machine} · {e.time}</small></div><StatusPill value={e.severity}/></div>):<div className="quiet"><ShieldCheck size={34}/><b>Telemetry quiet</b><span>Start a cyber-range scenario to generate synthetic security events.</span></div>}</div></section></div>
<div className="dashboard-grid lower"><section className="panel"><div className="panel-head"><div><span className="panel-kicker">RISK DISTRIBUTION</span><h2>Machine Posture</h2></div></div><div className="donut-wrap"><div className="donut" style={{'--risk':`${Math.min(95,risky*5)}%`} as any}><div><strong>{machines.filter((m:Machine)=>m.status==='HEALTHY').length}</strong><span>healthy</span></div></div><div className="legend"><span><i className="lg healthy"/>Healthy <b>{machines.filter((m:Machine)=>m.status==='HEALTHY').length}</b></span><span><i className="lg suspicious"/>Investigate <b>{risky}</b></span><span><i className="lg compromised"/>Compromised <b>{critical}</b></span></div></div></section><section className="panel span-2"><div className="panel-head"><div><span className="panel-kicker">CURRENT CASE</span><h2>{incident?.title||'No active incident'}</h2></div>{incident&&<StatusPill value={incident.severity}/>}</div>{incident?<div className="incident-brief"><div><small>CASE</small><b>{incident.id}</b></div><div><small>RISK</small><b>{incident.risk}/100</b></div><div><small>CONFIDENCE</small><b>{incident.confidence}%</b></div><div><small>ASSETS</small><b>{incident.assets.length}</b></div><div><small>STATE</small><b>{incident.status}</b></div><button className="primary" onClick={()=>setPage('incidents')}>Investigate <ArrowRight size={16}/></button></div>:<div className="mission-callout"><Swords size={28}/><div><b>Launch a controlled cyber-range exercise</b><span>Simulate a defensive incident across the 20-machine laboratory.</span></div><button className="primary" onClick={()=>setPage('range')}>Open Cyber Range</button></div>}</section></div></>}

function WarRoom({machines,incident,events,running,onContain,onReset}:any){return <div className="war-grid"><section className="panel war-topology"><div className="panel-head"><div><span className="panel-kicker">LIVE ATTACK GRAPH</span><h2>{incident?.title||'Environment baseline'}</h2></div>{running?<span className="live-chip"><i/>SIMULATION ACTIVE</span>:incident&&<StatusPill value={incident.status}/>}</div><Topology machines={machines}/></section><section className="panel war-timeline"><div className="panel-head"><div><span className="panel-kicker">UNIFIED TIMELINE</span><h2>Security Events</h2></div><span>{events.length} events</span></div><Timeline events={events}/></section><section className="panel war-machines"><div className="panel-head"><div><span className="panel-kicker">INFRASTRUCTURE</span><h2>20 Machine Status</h2></div></div><div className="mini-machine-grid">{machines.map((m:Machine)=><div key={m.id} className={`mini-machine mini-${m.status.toLowerCase()}`}><span/><div><b>{m.name}</b><small>{m.zone}</small></div><strong>{m.risk}</strong></div>)}</div></section><section className="panel war-response"><div className="panel-head"><div><span className="panel-kicker">RESPONSE</span><h2>Incident Controls</h2></div></div><div className="response-stack"><button className="danger-action" disabled={!incident} onClick={onContain}><ShieldOff size={18}/><div><b>Contain affected lab assets</b><span>Simulated isolation only</span></div></button><button className="secondary-action" onClick={onReset}><RotateCcw size={18}/><div><b>Reset cyber range</b><span>Return all machines to baseline</span></div></button></div></section></div>}

function Incidents({incident,events,setPage}:any){return <>{!incident?<Empty title="No active incidents" text="Start a cyber-range exercise to create a case with evidence, timeline and attack-path reconstruction."/>:<div className="incident-layout"><section className="panel incident-main"><div className="case-head"><div><span className="panel-kicker">{incident.id}</span><h2>{incident.title}</h2><p>Correlated evidence from the synthetic lab environment.</p></div><div className="case-status"><StatusPill value={incident.severity}/><b>{incident.risk}/100</b><small>RISK SCORE</small></div></div><div className="case-stats"><div><small>STATE</small><b>{incident.status}</b></div><div><small>CONFIDENCE</small><b>{incident.confidence}%</b></div><div><small>ASSETS</small><b>{incident.assets.length}</b></div><div><small>USERS</small><b>{incident.users.length}</b></div><div><small>EVIDENCE EVENTS</small><b>{events.length}</b></div></div><div className="panel-subhead"><h3>Attack-path reconstruction</h3><button className="text-btn" onClick={()=>setPage('investigation')}>Full investigation <ArrowRight size={15}/></button></div><AttackGraph incident={incident}/><div className="panel-subhead"><h3>Evidence timeline</h3></div><Timeline events={events}/></section><aside className="panel case-aside"><span className="panel-kicker">SOURCE ANALYSIS</span><h3>Network infrastructure</h3><div className="source-card"><Globe2 size={28}/><strong>{incident.sourceIp}</strong><span>{incident.city}, {incident.country}</span></div>{[['ASN',incident.asn],['PROVIDER',incident.provider],['ATTRIBUTION CONFIDENCE',incident.attributionConfidence],['RELATED ASSETS',incident.assets.join(', ')]].map(([a,b])=><div className="kv" key={a}><small>{a}</small><b>{b}</b></div>)}<div className="notice"><AlertTriangle size={17}/><p>Network geolocation indicates probable infrastructure location. It does not establish a person's exact physical location or identity.</p></div><button className="primary wide" onClick={()=>setPage('recovery')}>Open response & recovery</button></aside></div>}</>}

function Machines({machines,selected,setSelected}:any){return <><div className="toolbar"><div className="searchbox"><Search size={16}/><input placeholder="Search machine, IP, zone..."/></div><button className="ghost"><Filter size={16}/> Filters</button><span className="toolbar-count">20 managed machines</span></div><div className="machine-grid">{machines.map((m:Machine)=><MachineCard key={m.id} machine={m} onSelect={setSelected}/>)}</div>{selected&&<div className="drawer"><button className="drawer-close" onClick={()=>setSelected(null)}><X/></button><span className="panel-kicker">MACHINE INSPECTOR</span><h2>{selected.name}</h2><StatusPill value={selected.status}/><div className="drawer-score"><strong>{selected.risk}</strong><span>Risk score</span></div>{[['ROLE',selected.role],['ZONE',selected.zone],['IP ADDRESS',selected.ip],['OPERATING SYSTEM',selected.os],['CPU',`${selected.cpu}%`],['RAM',`${selected.ram}%`],['NETWORK',`${selected.network}%`],['ACTIVE ALERTS',String(selected.alerts)]].map(([k,v])=><div className="kv" key={k}><small>{k}</small><b>{v}</b></div>)}</div>}</>}

function NetworkPage({machines,events}:any){return <div className="dashboard-grid"><section className="panel span-2"><div className="panel-head"><div><span className="panel-kicker">NETWORK DEFENSE</span><h2>Zone topology & correlated paths</h2></div><span className="live-chip"><i/>SENSOR ONLINE</span></div><Topology machines={machines}/></section><section className="panel"><div className="panel-head"><div><span className="panel-kicker">FLOW SUMMARY</span><h2>Network baseline</h2></div></div><div className="metric-stack">{[['ACTIVE SESSIONS','3,482'],['DNS EVENTS / MIN','1,204'],['TLS SESSIONS','892'],['SYNTHETIC ALERTS',String(events.length)],['SENSOR','SOC-SENSOR-01']].map(([a,b])=><div className="metric-row" key={a}><span>{a}</span><b>{b}</b></div>)}</div><div className="spark-bars">{[38,55,44,66,51,73,61,48,70,58,82,63,72,50,46,64,57,79,69,60].map((h,i)=><i key={i} style={{height:h+'%'}}/>)}</div></section></div>}

function Investigation({incident,events}:any){return <>{!incident?<Empty title="Nothing to reconstruct yet" text="Run a scenario and the correlation engine will build an attack path from observed evidence."/>:<div className="dashboard-grid"><section className="panel span-2"><div className="panel-head"><div><span className="panel-kicker">INVESTIGATION GRAPH</span><h2>Correlated entities & attack path</h2></div><StatusPill value={incident.severity}/></div><AttackGraph incident={incident}/><div className="graph-evidence"><div><small>OBSERVED SOURCE</small><b>{incident.sourceIp}</b></div><div><small>AFFECTED ASSETS</small><b>{incident.assets.length}</b></div><div><small>TACTICS</small><b>{incident.techniques.length}</b></div><div><small>CONFIDENCE</small><b>{incident.confidence}%</b></div></div></section><section className="panel"><div className="panel-head"><div><span className="panel-kicker">EVIDENCE SOURCES</span><h2>Correlation inputs</h2></div></div><div className="metric-stack">{[['WAZUH EVENTS',String(events.length*3+11)],['SURICATA ALERTS',String(events.length+3)],['ZEEK SESSIONS',String(events.length*7+17)],['ENDPOINT EVENTS',String(events.length*5+22)],['IDENTITY EVENTS',String(events.length*2+5)]].map(([a,b])=><div className="metric-row" key={a}><span>{a}</span><b>{b}</b></div>)}</div></section></div>}</>}

function Forensics({incident,events}:any){return <div className="dashboard-grid"><section className="panel span-2"><div className="panel-head"><div><span className="panel-kicker">DIGITAL FORENSICS</span><h2>Evidence Locker</h2></div><span className="micro-chip">CHAIN OF CUSTODY</span></div>{incident?<div className="evidence-table"><div className="table-head"><span>ID</span><span>TYPE</span><span>SOURCE</span><span>INTEGRITY</span><span>CASE</span></div>{events.map((e:TimelineEvent,i:number)=><div className="table-row" key={e.id}><span>EVD-{String(291+i).padStart(6,'0')}</span><span>{e.source.includes('Response')?'Response Artifact':'Telemetry Artifact'}</span><span>{e.machine}</span><span className="verified"><FileCheck2 size={15}/> VERIFIED</span><span>{incident.id}</span></div>)}</div>:<Empty title="Evidence locker empty" text="Evidence objects appear here when a case is opened."/>}</section><section className="panel"><div className="panel-head"><div><span className="panel-kicker">FORENSIC READINESS</span><h2>Collection status</h2></div></div><div className="health-ring"><div><strong>98%</strong><span>ready</span></div></div><div className="metric-stack compact">{[['Endpoint collector','ONLINE'],['Artifact storage','ONLINE'],['Hash verification','ENABLED'],['Retention policy','30 DAYS']].map(([a,b])=><div className="metric-row" key={a}><span>{a}</span><b>{b}</b></div>)}</div></section></div>}

function Intel({incident}:any){return <div className="dashboard-grid"><section className="panel span-2"><div className="panel-head"><div><span className="panel-kicker">THREAT INTELLIGENCE</span><h2>Indicator enrichment</h2></div><div className="searchbox small"><Search size={16}/><input placeholder="IP, domain, URL, hash, ASN..."/></div></div>{incident?<div className="intel-hero"><div className="intel-score"><Globe2/><strong>{incident.sourceIp}</strong><span>Network indicator</span></div><div className="intel-grid">{[['COUNTRY ESTIMATE',incident.country],['CITY ESTIMATE',incident.city],['ASN',incident.asn],['PROVIDER',incident.provider],['INFRASTRUCTURE TYPE','Hosting / Datacenter'],['VPN / PROXY','Possible'],['TOR MATCH','No lab match'],['CONFIDENCE',incident.attributionConfidence]].map(([a,b])=><div key={a}><small>{a}</small><b>{b}</b></div>)}</div><div className="notice"><AlertTriangle size={17}/><p>Attribution is an evidence assessment. Approximate IP geolocation and hosting metadata cannot identify the physical operator with certainty.</p></div></div>:<Empty title="No indicators observed" text="Start an exercise to enrich source infrastructure and related indicators."/>}</section><section className="panel"><div className="panel-head"><div><span className="panel-kicker">INTEL SOURCES</span><h2>Enrichment pipeline</h2></div></div><div className="source-list">{['ASN / RDAP','GeoIP Provider','Internal Reputation','Historical Incidents','DNS Intelligence','Certificate Intelligence'].map((x,i)=><div key={x}><span className="source-icon">{i+1}</span><div><b>{x}</b><small>Adapter ready / demo data</small></div><CheckCircle2 size={17}/></div>)}</div></section></div>}

function Mitre({incident}:any){const tactics=['Reconnaissance','Initial Access','Execution','Persistence','Privilege Escalation','Credential Access','Discovery','Lateral Movement','Collection','Command and Control','Exfiltration','Impact'];return <section className="panel"><div className="panel-head"><div><span className="panel-kicker">MITRE ATT&CK MAPPING</span><h2>Incident tactical coverage</h2></div><span className="micro-chip">ENTERPRISE</span></div><div className="mitre-grid">{tactics.map((t,i)=>{const hit=incident?.techniques?.includes(t)|| (incident&&i<Math.min(incident.techniques.length+2,6)); const pct=hit?55+((i*13)%45):8+((i*7)%18);return <div className={`mitre-card ${hit?'hit':''}`} key={t}><span>{String(i+1).padStart(2,'0')}</span><strong>{t}</strong><div className="bar"><i style={{width:pct+'%'}}/></div><small>{hit?'Observed / correlated':'No current evidence'}</small></div>})}</div></section>}

function Recovery({incident,machines,onContain,onRecover}:any){const affected=incident?.assets||[];const isolated=machines.filter((m:Machine)=>affected.includes(m.name)&&m.status==='ISOLATED').length;const recovered=machines.filter((m:Machine)=>affected.includes(m.name)&&m.status==='RECOVERED').length;return <div className="recovery-layout"><section className="panel"><div className="panel-head"><div><span className="panel-kicker">RECOVERY ORCHESTRATOR</span><h2>Production recovery plan</h2></div>{incident&&<StatusPill value={incident.status}/>}</div>{incident?<><div className="recovery-flow">{[['01','Contain','Affected lab assets isolated',isolated>0||recovered>0],['02','Preserve','Evidence locker + hashes verified',true],['03','Restore','Clean snapshot / replica selected',recovered>0],['04','Validate','Files, DB and service checks',recovered>0],['05','Return','Production baseline restored',incident.status==='CLOSED']].map(([n,t,d,done]:any)=><div className={done?'done':''} key={n}><span>{done?<CheckCircle2 size={20}/>:n}</span><div><b>{t}</b><small>{d}</small></div></div>)}</div><div className="action-row"><button className="danger-action" onClick={onContain}><ShieldOff size={18}/>Contain affected assets</button><button className="primary" disabled={!isolated||recovered>0} onClick={onRecover}><DatabaseBackup size={18}/>Restore & verify clean state</button></div></>:<Empty title="No recovery operation required" text="Start and investigate a scenario first."/>}</section><section className="panel recovery-verify"><span className="panel-kicker">INTEGRITY VERIFICATION</span><h2>{recovered?'RECOVERY VERIFIED':'WAITING FOR RESTORE'}</h2><div className={`verify-orb ${recovered?'pass':''}`}>{recovered?<CheckCircle2 size={40}/>:<Clock3 size={40}/>}</div>{[['Expected lab files','284,921'],['Recovered lab files',recovered?'284,921':'—'],['Missing',recovered?'0':'—'],['Unexpected',recovered?'0':'—'],['Hash mismatch',recovered?'0':'—'],['Database integrity',recovered?'PASS':'PENDING'],['Persistence scan',recovered?'PASS':'PENDING'],['Network baseline',recovered?'PASS':'PENDING']].map(([a,b])=><div className="metric-row" key={a}><span>{a}</span><b className={b==='PASS'||b==='0'?'good':''}>{b}</b></div>)}</section></div>}

function Range({running,onStart,onReset}:any){return <><div className="range-hero"><div><span className="panel-kicker">ISOLATED DEFENSIVE LAB</span><h2>20-machine Enterprise Cyber Range</h2><p>Generate controlled synthetic incidents, investigate them, contain affected lab assets, preserve evidence and restore your own data from clean recovery points.</p></div><div className="range-status"><span className={running?'active':''}/><b>{running?'EXERCISE RUNNING':'RANGE READY'}</b><small>External targets disabled</small></div></div><div className="scenario-grid">{scenarios.map(s=><div className="scenario-card" key={s.id}><div className="scenario-head"><span>{s.difficulty}</span><div className={`difficulty d-${s.difficulty.toLowerCase()}`}>{'★'.repeat(['Beginner','Intermediate','Advanced','Expert'].indexOf(s.difficulty)+1)}{'☆'.repeat(3-['Beginner','Intermediate','Advanced','Expert'].indexOf(s.difficulty))}</div></div><Swords size={24}/><h3>{s.title}</h3><p>{s.description}</p><div className="scenario-target"><small>PRIMARY OBSERVATION</small><b>{s.target}</b></div><button className="primary wide" disabled={!!running} onClick={()=>onStart(s.id)}><Play size={16}/>Start exercise</button></div>)}</div><div className="range-footer"><div className="notice"><ShieldCheck size={18}/><p>All scenarios generate synthetic telemetry inside the local application/cyber-range model. They do not scan, exploit, persist on, or exfiltrate from external systems.</p></div><button className="ghost" onClick={onReset}><RotateCcw size={16}/>Reset range</button></div></>}

function AI({incident,events}:any){const answer=incident?`SENTINEL-X correlated ${events.length} primary timeline events into ${incident.id}. The highest-risk path currently involves ${incident.assets.join(' → ')}. Investigation confidence is ${incident.confidence}%. Priority: preserve evidence, validate affected identities, contain the lab assets if compromise is confirmed, then recover from a clean snapshot.`:'No active incident is available. Start a cyber-range exercise and I will summarize only the evidence generated by the lab.';return <div className="ai-layout"><section className="panel ai-main"><div className="ai-head"><div className="ai-logo"><Sparkles/></div><div><span className="panel-kicker">EVIDENCE-GROUNDED ANALYST</span><h2>TITAN AI</h2></div><span className="micro-chip">NO UNGROUNDED CLAIMS</span></div><div className="chat"><div className="message user"><span>ANALYST</span>What happened, and what should I investigate next?</div><div className="message ai"><span>TITAN AI</span>{answer}<div className="evidence-chips"><i>Wazuh {events.length*3+11}</i><i>Suricata {events.length+3}</i><i>Zeek {events.length*7+17}</i><i>Endpoint {events.length*5+22}</i></div></div></div><div className="promptbar"><input placeholder="Ask about this incident, asset, alert or recovery state..."/><button><ArrowRight/></button></div></section><aside className="panel"><span className="panel-kicker">SUGGESTED QUESTIONS</span><div className="suggestions">{['Which asset has the highest risk?','Explain the current attack path.','Which MITRE tactics were observed?','What evidence supports this incident?','Is recovery safe to start?'].map(q=><button key={q}><Bot size={16}/>{q}</button>)}</div><div className="notice"><ShieldCheck size={17}/><p>AI explanations are designed to reference available evidence and avoid inventing attacker identity, location or activity.</p></div></aside></div>}

function Reports({incident}:any){return <div className="dashboard-grid"><section className="panel span-2"><div className="panel-head"><div><span className="panel-kicker">EXECUTIVE & TECHNICAL REPORTING</span><h2>Incident reporting workspace</h2></div><button className="primary" disabled={!incident}><FileCheck2 size={16}/>Generate report</button></div><div className="report-preview"><div className="report-cover"><ShieldCheck/><span>SENTINEL-X TITAN</span><h2>{incident?.title||'Incident Response Report'}</h2><p>{incident?.id||'Run an exercise to populate report data'}</p></div><div className="report-sections">{['Executive Summary','Incident Scope','Detection & Timeline','Affected Assets','Evidence & Chain of Custody','Threat Source Assessment','MITRE Mapping','Containment Actions','Recovery Verification','Lessons Learned'].map((x,i)=><div key={x}><span>{String(i+1).padStart(2,'0')}</span><b>{x}</b><CheckCircle2 size={16}/></div>)}</div></div></section><section className="panel"><span className="panel-kicker">EXPORTS</span><h2>Available formats</h2><div className="metric-stack">{[['PDF','Executive / technical'],['JSON','Case data'],['CSV','Timeline / indicators'],['STIX-style','Threat intel model']].map(([a,b])=><div className="metric-row" key={a}><b>{a}</b><span>{b}</span></div>)}</div></section></div>}

function Users(){const roles=[['Platform Administrator','Full platform control'],['SOC Manager','Operations & approvals'],['SOC Analyst L1','Triage and case notes'],['SOC Analyst L2','Investigation and hunts'],['SOC Analyst L3','Advanced response'],['Threat Hunter','Cross-data hunting'],['DFIR Analyst','Evidence and forensics'],['Auditor','Read-only compliance']];return <section className="panel"><div className="panel-head"><div><span className="panel-kicker">ZERO-TRUST ADMINISTRATION</span><h2>Roles & least-privilege access</h2></div><button className="primary">Add user</button></div><div className="role-grid">{roles.map(([r,d],i)=><div className="role-card" key={r}><span className="role-icon">{String(i+1).padStart(2,'0')}</span><div><b>{r}</b><small>{d}</small></div><span className="micro-chip">ENABLED</span></div>)}</div></section>}

function Settings(){return <div className="settings-grid">{[['Telemetry','Event streaming, retention and normalization'],['Detection Engine','Rule packs, thresholds and behavioral baselines'],['Integrations','Wazuh, Suricata, Zeek, Velociraptor adapters'],['Recovery','Snapshots, replicas, integrity policy'],['Cyber Range','Isolation, scenario reset and synthetic datasets'],['Audit','Immutable administrator activity trail']].map(([t,d])=><section className="panel setting" key={t}><span className="panel-kicker">PLATFORM</span><h3>{t}</h3><p>{d}</p><div className="toggle-row"><span>Status</span><label className="toggle"><input type="checkbox" defaultChecked/><i/></label></div></section>)}</div>}

function Empty({title,text}:{title:string,text:string}){return <div className="empty-state big"><div className="radar-orb"/><h2>{title}</h2><p>{text}</p></div>}
