using SentinelX.Gateway.Models;
namespace SentinelX.Gateway.Services;
public sealed class LabStateService {
  private readonly object _gate=new();
  public List<Machine> Machines {get;private set;}=SeedMachines();
  public List<Incident> Incidents {get;private set;}=[];
  public object Overview(){lock(_gate){var critical=Machines.Count(x=>x.Status=="COMPROMISED");var risk=Machines.Count(x=>x.Status is "SUSPICIOUS" or "HIGH_RISK" or "COMPROMISED");return new{machines=Machines.Count,critical,risk,activeIncidents=Incidents.Count(x=>x.Status!="CLOSED"),securityScore=Math.Max(10,100-risk*4-critical*8)};}}
  public void Reset(){lock(_gate){Machines=SeedMachines();Incidents=[];}}
  public void SetIncident(Incident incident){lock(_gate){Incidents.RemoveAll(x=>x.Status!="CLOSED");Incidents.Add(incident);}}
  public void ApplyEvent(Incident incident, SecurityEvent e){lock(_gate){incident.Timeline.Add(e);incident.Techniques.Add(e.Tactic);incident.Status=incident.Timeline.Count==1?"TRIAGED":"INVESTIGATING";var m=Machines.FirstOrDefault(x=>x.Name==e.Machine);if(m!=null){m.Status=e.Severity=="CRITICAL"?"COMPROMISED":e.Severity=="HIGH"?"HIGH_RISK":"SUSPICIOUS";m.Risk=e.Severity=="CRITICAL"?96:e.Severity=="HIGH"?82:55;m.Alerts++;m.Network=Math.Min(99,m.Network+25);}}}
  public bool Contain(string id){lock(_gate){var i=Incidents.FirstOrDefault(x=>x.Id==id);if(i==null)return false;i.Status="CONTAINING";foreach(var m in Machines.Where(x=>i.Assets.Contains(x.Name)&&x.Status!="HEALTHY")){m.Status="ISOLATED";m.Network=3;m.Risk=Math.Max(35,m.Risk-30);}return true;}}
  public bool Recover(string id){lock(_gate){var i=Incidents.FirstOrDefault(x=>x.Id==id);if(i==null)return false;i.Status="CLOSED";i.Risk=9;i.Confidence=99;foreach(var m in Machines.Where(x=>i.Assets.Contains(x.Name))){m.Status="RECOVERED";m.Risk=6;m.Alerts=0;m.Cpu=22;m.Network=14;}return true;}}
  static List<Machine> SeedMachines()=>[
new("edge-fw","EDGE-FW-01","Firewall / Gateway","EDGE","10.10.0.1","Network OS"),new("waf","WAF-01","Web Application Firewall","DMZ","10.20.0.2","Linux"),new("lb","LB-01","Load Balancer","DMZ","10.20.0.3","Linux"),new("web1","WEB-PROD-01","Production Web Server","DMZ","10.20.10.11","Ubuntu 24.04"),new("web2","WEB-PROD-02","Production Web Server","DMZ","10.20.10.12","Ubuntu 24.04"),new("api1","API-PROD-01","Backend API","APPLICATION","10.30.10.21","Ubuntu 24.04"),new("api2","API-PROD-02","Backend API","APPLICATION","10.30.10.22","Ubuntu 24.04"),new("db1","DB-PRIMARY-01","Primary Database","DATA","10.40.10.31","PostgreSQL/Linux"),new("db2","DB-REPLICA-01","Database Replica","DATA","10.40.10.32","PostgreSQL/Linux"),new("file","FILE-SRV-01","Company File Server","INTERNAL","10.50.10.41","Windows Server"),new("ad","AD-DC-01","Identity / Directory","IDENTITY","10.50.20.11","Windows Server"),new("dns","DNS-01","Internal DNS","INFRASTRUCTURE","10.50.20.12","Linux"),new("mail","MAIL-01","Mail Simulator","INFRASTRUCTURE","10.50.20.13","Linux"),new("devops","DEVOPS-01","CI/CD Platform","ENGINEERING","10.50.30.21","Ubuntu 24.04"),new("devpc","DEV-PC-01","Developer Workstation","USER","10.60.10.101","Windows 11"),new("finpc","FIN-PC-01","Finance Workstation","USER","10.60.10.102","Windows 11"),new("hrpc","HR-PC-01","HR Workstation","USER","10.60.10.103","Windows 11"),new("backup","BACKUP-01","Immutable Backup Vault","RECOVERY","10.70.10.10","Hardened Linux"),new("sensor","SOC-SENSOR-01","IDS / NSM Sensor","SECURITY","10.80.10.10","Security Linux"),new("range","RANGE-SIM-01","Isolated Event Simulator","CYBER RANGE","172.20.0.10","Isolated Linux")];
}
